# Generated by Django 2.2 on 2021-10-18 20:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='otros_comentarios',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Otros Comentarios'),
        ),
        migrations.AlterField(
            model_name='serviciopresupuesto',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviciopresupuesto',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Presupuesto'),
        ),
    ]
